- name: Create Resources Folder
  file:
    path: "{{ docker_folder }}"
    state: directory

- name: Clone
  git:
    repo: "http://{{ username }}:{{ password }}@github.com/JMSAPIT1234/tomcat.git"
    dest: "{{ docker_folder }}"

- name: Download war file
  get_url:
    url: http://34.229.10.94/nexus/content/repositories/snapshots/DTSActivity/CurrencyConverter/1/CurrencyConverter-1.war
    dest: "{{ docker_folder }}/resources"
    mode: 0644
    url_password: "{{ password }}"
    url_username: "{{ username }}"
